### ISSUE TITLE
h4s-spring-petclinic-reactjs :: com.hdivsecurity dependency

### ISSUE THREAD

**Issue by ranjit909** [hdiv/h4s-spring-petclinic-reactjs#1]
Missing artifact com.hdivsecurity:hdiv-for-services:jar:1.7.51-SNAPSHOT

<dependency>
			<groupId>com.hdivsecurity</groupId>
			<artifactId>hdiv-for-services</artifactId>
			<version>1.7.51-SNAPSHOT</version>
		</dependency>

**Comment by gillarramendi** [comment]
Hdiv for ReactJS is part of Hdiv Enterprise RASP solution.
> https://hdivsecurity.com/runtime-application-self-protection-rasp

You can ask for a trial demo in the web if you want to try it.
